name: Pull Latest from Source
on:
  repository_dispatch:
    types: [source_pushed]

jobs:
  pull_sync_and_build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Dest Repo
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}
          fetch-depth: 0

      # 2. Pull from Source Repo 
      - name: Pull from Source Repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          # Add the source repo using your Read-Only token
          git remote add source_repo https://${{ secrets.REPO_TOKEN }}@github.com/TCCD-CUFE/tccd-web-frontend
          
          # Pull and merge the code
          git pull source_repo main --no-rebase --allow-unrelated-histories

      # 3. Test React Build
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' 

      - name: Install Dependencies
        run: npm install 

      - name: Test React Build
        run: npm run build 

      # 4. Push if Build Succeeds
      - name: Push changes
        run: |
          git push origin main
